raxjs/rax-app

packages/rax-plugin-app/package.json
add rax-plugin-app 0.1.14:
* add webpack copy plugin
* add PWA snapshot support
=> feat: publish rax-plugin-app

packages/rax-plugin-ssr/package.json, packages/rax-plugin-ssr/src/ssr/extractSourceMap.js, packages/rax-plugin-ssr/src/ssr/parseEvalStackTrace.js, packages/rax-plugin-ssr/src/ssr/setDev.js
Closed https://github.com/alibaba/rax/issues/1323
=> fix: improve error stack readability when executing SSR with dev server

packages/rax-scripts/package.json
Closes https://github.com/raxjs/rax-scripts/issues/5
=> fix: listen EADDRINUSE :::9369 when using node debug

packages/rax-plugin-app/package.json, packages/rax-plugin-app/src/config/getWebpackBase.js, packages/rax-plugin-app/src/config/user/keys/inlineStyle.js, packages/rax-plugin-app/src/config/web/getBase.js, packages/rax-plugin-app/src/config/weex/getBase.js, packages/rax-plugin-component/package.json, packages/rax-scripts/package.json, packages/rax-template/package.json, packages/rax-template/template/scaffold/package.json.ejs, packages/rax-template/template/scaffold/src/app.js.ejs
=> [Release]scripts-0911

packages/rax-plugin-faas/src/funcBuilder/buildFunctions.js, packages/rax-plugin-faas/src/funcBuilder/constants.js, packages/rax-plugin-faas/src/funcBuilder/generateFuncPath.js, packages/rax-plugin-faas/src/funcBuilder/index.js, packages/rax-plugin-faas/src/index.js
build functions to .serverless dir
=> feat: build function dependencies

packages/rax-plugin-app/package.json, packages/rax-plugin-app/src/config/weex/getBase.js, packages/rax-plugin-component/package.json, packages/rax-plugin-component/src/config/getBaseWebpack.js, packages/rax-plugin-component/src/config/user/default.config.js, packages/rax-plugin-component/src/config/user/keys/exclude.js, packages/scripts-core/package.json, packages/scripts-core/src/commands/dev.js, packages/scripts-core/src/core/Context.js
=> [Release]scripts-0919

README.md, packages/rax-cli/README.md, packages/rax-compile-config/README.md, packages/rax-plugin-api/README.md, packages/rax-plugin-app/README.md, packages/rax-plugin-component/README.md, packages/rax-plugin-faas/README.md, packages/rax-plugin-multi-pages/README.md, packages/rax-plugin-pwa/README.md, packages/rax-plugin-ssr/README.md, packages/rax-scripts/README.md, packages/rax-template/README.md, packages/scripts-core/README.md
=> [Feat]add readme

packages/rax-plugin-app/package.json, packages/rax-plugin-app/src/config/web/getBase.js, packages/rax-plugin-app/src/plugins/PWAAppShellPlugin.js
fix: 
* app.json shell source config not working.
* App Shell can't use hooks.
* rax-scripts build shell undefined
=> fix: App Shell

packages/rax-plugin-compat-react/README.md, packages/rax-plugin-compat-react/package.json, packages/rax-plugin-compat-react/src/index.js
=> [Feat] Add react compat plugin

packages/rax-plugin-ssr/package.json, packages/rax-plugin-ssr/src/ssr/loader.js
=> Fix ssr init props

packages/rax-compile-config/src/hmr/webpackHotDevClient.entry.js
if (window.location.protocol === 'https') -> if (window.location.protocol === 'https:')
=> fix: incorrect location.protocol if-statement

packages/rax-plugin-app/package.json, packages/rax-plugin-app/src/loaders/AppConfigLoader/index.js
support: 
```json
// app.json
{
"routes": [
{
"path": "/",
"keepAlive": true,
"source": "pages/Home/index"
}
]
}
```
=> feat: rax-pwa upgrade

packages/rax-compile-config/src/getBabelConfig.js
https://babeljs.io/docs/en/babel-preset-react#throwifnamespace
fix: alibaba/rax#1539
=> feat: support namespace attr and tag for xml

packages/rax-cli/bin/rax.js, packages/rax-compile-config/src/hmr/formatWebpackMessages.js, packages/rax-compile-config/src/hmr/moduleHotAccept.loader.js, packages/rax-compile-config/src/hmr/webpackHotDevClient.entry.js, packages/rax-compile-config/src/platformLoader/TraverseImport.js, packages/rax-plugin-app/src/plugins/PWAAppShellPlugin.js, packages/rax-plugin-app/src/plugins/WeexFrameworkBannerPlugin.js, packages/rax-plugin-component/src/plugins/WeexFrameworkBannerPlugin.js, packages/rax-plugin-pwa/src/plugins/SaveToDesktopPlugin.js, packages/rax-plugin-pwa/src/plugins/SnapshotPlugin.js, packages/scripts-core/src/core/Context.js
=> fix: eslint error

packages/build-plugin-rax-component/package.json, packages/build-plugin-rax-component/src/dev.js
1. `options[type]` should have a default value
2. miniapp/wechat miniprogram dev server is started repeatedly
=> fix: component plugin dev mode

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/loaders/AppConfigLoader/index.js
See: https://github.com/alibaba/rax/issues/1626
=> Fix routeProps

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/plugins/UniversalDocumentPlugin.js, packages/build-plugin-rax-ssr/package.json, packages/build-plugin-rax-ssr/src/ssr/getBase.js, packages/build-plugin-rax-ssr/src/ssr/loader.js
1. Get output path of html by filename instead of hard code.
2. External Weex module in SSR
3. Add Loader for Midway FaaS
=> Feat: support for Midway FaaS

packages/rax-generator/package.json, packages/rax-generator/src/template/app/package.json.ejs, packages/rax-generator/src/template/app/src/components/Logo/index.jsx.ejs
* Update rax-app version
rax-app ^0.2.0  -> rax-app ^1.0.0 
https://unpkg.com/rax-app@1.0.0/lib/index.js
* Update component source schema（For Universal App）
=> feat: update rax-generator

packages/rax-compile-config/src/platformLoader/TraverseImport.js
fix https://github.com/alibaba/rax/issues/1647
=> feat: traverseImport add babel plugin "optionalChaining" and "nullishCoalescingOperator"

packages/rax-generator/README.md, packages/rax-generator/package.json, packages/rax-generator/src/config/index.js, packages/rax-generator/src/template/app/build.json.ejs, packages/rax-generator/src/template/app/package.json.ejs, packages/rax-generator/src/template/app/src/app.js.ejs, packages/rax-generator/src/template/app/src/app.json.ejs, packages/rax-generator/src/template/app/src/components/Logo/index.jsx.ejs, packages/rax-generator/src/template/app/src/document/index.jsx.ejs, packages/rax-generator/src/template/app/src/pages/Home/index.jsx.ejs
=> feat: compatibility with React

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/plugins/UniversalDocumentPlugin.js
fix [https://github.com/alibaba/rax/issues/1672](https://github.com/alibaba/rax/issues/1672)
=> Fix rax-document empty Styles

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/plugins/UniversalDocumentPlugin.js
=> feat: compact react for document

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/config/web/setDev.js, packages/build-plugin-rax-multi-pages/package.json, packages/build-plugin-rax-multi-pages/src/setDevServer.js, packages/rax-compile-config/package.json, packages/rax-compile-config/src/hmr/webpackHotDevClient.entry.js
=> fix: build not response in devServer

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/plugins/UniversalDocumentPlugin.js
=> Feat remove dangerouslySetInnerHTML in UniversalDocumentPlugin.js

packages/build-plugin-multi-demo-portal/package.json, packages/build-plugin-multi-demo-portal/src/config/demo.html, packages/build-plugin-multi-demo-portal/src/config/getBaseWebpack.js, packages/build-plugin-multi-demo-portal/src/config/getDistConfig.js, packages/build-plugin-multi-demo-portal/src/config/template/portal.hbs, packages/build-plugin-multi-demo-portal/src/config/utils/generatePortalJs.js, packages/build-plugin-multi-demo-portal/src/loaders/MarkdownLoader/index.js
generate demo pages showing in device box for the material presentation
=> fix: demo page missing in iframe

packages/rax-generator/package.json, packages/rax-generator/src/template/component/src/index.tsx.ejs
=> fix: remove interface export to fix build error  and upgrade version

packages/build-plugin-multi-demo-portal/package.json, packages/build-plugin-multi-demo-portal/src/config/demo.html, packages/build-plugin-multi-demo-portal/src/config/getDistConfig.js, packages/build-plugin-multi-demo-portal/src/config/template/portal.hbs, packages/build-plugin-multi-demo-portal/src/dev.js
change the generated html file path : ` build/portal.html → build/index.html`
=> fix: unify material access path

packages/build-plugin-rax-multi-pages/package.json, packages/build-plugin-rax-multi-pages/src/template/main.jsx.ejs, packages/build-plugin-rax-ssr/package.json, packages/build-plugin-rax-ssr/src/template/main.jsx.ejs
多页应用 demo 预览支持新开页面方式与本页面刷新方式，通过页面参数进行区分
为了解决在 webide 中 demo 预览的体验问题，防止外跳到浏览器
=> feat: use js open new page

packages/build-plugin-rax-app/src/config/ssr/getBase.js, packages/build-plugin-rax-app/src/config/user/keys/hash.js
fix https://github.com/raxjs/rax-scripts/issues/145
=> fix: reset filename error when hash is true

packages/rax-generator/package.json, packages/rax-generator/src/generator.js
Remove common new app project`/src/api/user/index.js` file
=> Fix common app project has api file

packages/babel-plugin-transform-jsx-stylesheet/package.json, packages/babel-plugin-transform-jsx-stylesheet/src/__tests__/index.js, packages/babel-plugin-transform-jsx-stylesheet/src/constants.js, packages/babel-plugin-transform-jsx-stylesheet/src/index.js
修复当项目为 css module 的时候 style 动态计算报错。
=> fix: error when inlineStyle is false and module is true

packages/build-plugin-rax-component/package.json
Add  `error-stack-tracey`  to dependencies
=> Fix: dependencies

packages/rax-cli/bin/rax.js
=> feat: add cli help message

packages/rax-generator/package.json, packages/rax-generator/src/template/app/package.json.ejs
new project update #187 dependencies.
=> Feat update rax-generator dependencies

packages/rax-miniapp-runtime-webpack-plugin/package.json, packages/rax-miniapp-runtime-webpack-plugin/src/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/tool/file-helper.js
- fix: native custom components can't be used in wechat miniprogram
- feat: support using native custom components in alibaba miniapp
- fix: can't generate page acss/wxss when turning off inlineStyle
=> feat(miniapp): support using native miniapp component

packages/build-plugin-rax-multi-pages/package.json, packages/build-plugin-rax-multi-pages/src/MulitPageLoader.js, packages/build-plugin-rax-multi-pages/src/formatPath.js, packages/rax-generator/package.json, packages/rax-generator/src/generator.js
=> Fix window path error

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/config/user/keys/inlineStyle.js
Fix miniapp runtime mode less support & minicss plugin register
=> fix(build-plugin-rax-app): miniapp runtime mode register minicss plugin

packages/build-plugin-rax-multi-pages/package.json, packages/build-plugin-rax-multi-pages/src/MulitPageLoader.js
```json
// app.json 
{
"shell": {
"source": "shell/index"
},
"hydrate": true
}
```
fix app.json hydrate not working in MPA.
=> Fix app.json hydrate not working in MPA

packages/rax-miniapp-runtime-webpack-plugin/package.json, packages/rax-miniapp-runtime-webpack-plugin/src/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/template/custom-component.js, packages/rax-miniapp-runtime-webpack-plugin/src/template/package.json, packages/rax-miniapp-runtime-webpack-plugin/src/template/page.js, packages/rax-miniapp-runtime-webpack-plugin/src/tool/file-helper.js
- Add API check before invoking to avoid error in DingTalk
- Remove dependencies in package.json to aovid IDE install tips
- Support tabbar config
- working in progress...
=> fix: support dingtalk miniapp

packages/rax-cli/bin/rax.js, packages/rax-cli/package.json
=> Feat rename the same project name

packages/rax-generator/package.json, packages/rax-generator/src/template/component/package.json.ejs, packages/rax-generator/src/template/component/src/js/style/index.js.ejs
- remove typescript syntax in js template
- add `miniappConfig` in component package.json which is missed
=> fix(rax-generator): update component template

packages/rax-miniapp-runtime-webpack-plugin/package.json, packages/rax-miniapp-runtime-webpack-plugin/src/index.js
- Tidy path resolve
- Fix the css file generation bug
- Export native custom component config
=>  fix(miniapp): path resolve && css file generate && custom component use

packages/stylesheet-loader/package.json
=> chore: update stylesheet-loader version

packages/build-plugin-rax-component/src/gulp/compile.js, packages/build-plugin-rax-component/src/gulp/gulpfile.js
=> feat: clear glup info

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/build.js, packages/build-plugin-rax-app/src/config/miniapp/compile/platformConfig.js, packages/build-plugin-rax-app/src/config/miniapp/targetPlatformMap.js, packages/build-plugin-rax-app/src/constants.js, packages/build-plugin-rax-app/src/dev.js, packages/build-plugin-rax-component/package.json, packages/build-plugin-rax-component/src/config/miniapp/getBase.js, packages/jsx2mp-loader/package.json, packages/jsx2mp-loader/src/script-loader.js, packages/jsx2mp-loader/src/utils/getAliasCorrespondingValue.js, packages/jsx2mp-loader/src/utils/isMiniappComponent.js, packages/rax-generator/package.json, packages/rax-generator/src/template/component/package.json.ejs, packages/rax-miniapp-config-webpack-plugin/package.json, packages/rax-miniapp-config-webpack-plugin/src/adaptConfig.js, packages/rax-miniapp-config-webpack-plugin/src/constants.js, packages/rax-quickapp-webpack-plugin/package.json, packages/rax-quickapp-webpack-plugin/src/generateManifest.js
- support bytedance microapp project
- fix alias bug in jsx2mp-loader
- optimize npm copy in component project
=> [RELEASE]: miniapp 0421 

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/loaders/MiniAppEntryLoader/index.js, packages/rax-miniapp-runtime-webpack-plugin/package.json, packages/rax-miniapp-runtime-webpack-plugin/src/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/templates/ali-miniapp/page.js, packages/rax-miniapp-runtime-webpack-plugin/src/templates/wechat-miniprogram/page.js
- 修复 app.js 引用 bundle 缺失的问题
- 配合 miniapp-render 修改 - 全局共享 window
- 移除无效代码
=> refactor(miniapp): window as global varaible

packages/build-plugin-rax-app/src/config/miniapp/compile/getBase.js, packages/build-plugin-rax-app/src/config/miniapp/runtime/getBase.js, packages/rax-miniapp-config-webpack-plugin/package.json, packages/rax-miniapp-config-webpack-plugin/src/index.js, packages/rax-miniapp-config-webpack-plugin/src/transformNativeConfig.js
```json
{
"plugins": [
[
"build-plugin-rax-app",
{
"targets": ["miniapp"],
"miniapp": {
"nativeConfig": {
"appId": 123
}
}
}
]
]
}
```
=> feat(miniapp): support configure native config

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/config/getWebpackBase.js
https://github.com/raxjs/rax-scripts/pull/301
improvement to perfermance
before
after
=> fix: sourcemap

packages/build-plugin-rax-app/src/config/miniapp/compile/getBase.js, packages/build-plugin-rax-app/src/config/miniapp/compile/setEntry.js, packages/build-plugin-rax-app/src/config/miniapp/filterNativePages.js, packages/build-plugin-rax-app/src/config/miniapp/pathHelper.js, packages/build-plugin-rax-app/src/config/miniapp/runtime/getBase.js, packages/build-plugin-rax-app/src/config/miniapp/runtime/setEntry.js, packages/build-plugin-rax-app/src/config/miniapp/targetPlatformMap.js, packages/build-plugin-rax-app/src/plugins/miniapp/CopyPublicFile.js
=> feat(miniapp): support using native pages

packages/build-plugin-rax-app/src/config/miniapp/runtime/getBase.js, packages/rax-miniapp-babel-plugins/package.json, packages/rax-miniapp-babel-plugins/src/index.js, packages/rax-miniapp-babel-plugins/src/plugins/babel-plugin-handle-custom-component.js, packages/rax-miniapp-babel-plugins/src/plugins/babel-plugin-native-lifecycle.js, packages/rax-miniapp-babel-plugins/src/utils/extMap.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/config.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/custom-component.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/page.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/pkg.js, packages/rax-miniapp-runtime-webpack-plugin/src/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/templates/ali-miniapp/root.xml.ejs, packages/rax-miniapp-runtime-webpack-plugin/src/templates/wechat-miniprogram/root.xml.ejs
=> feat: support with zero config use native custom compnent

packages/rax-miniapp-babel-plugins/src/plugins/babel-plugin-handle-custom-component.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/custom-component.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/page.js, packages/rax-miniapp-runtime-webpack-plugin/src/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/templates/ali-miniapp/root.xml.ejs, packages/rax-miniapp-runtime-webpack-plugin/src/templates/wechat-miniprogram/root.xml.ejs
- fix: native lifecycle generate
- fix: wechat miniprogram template
=> fix(miniapp): native component render

packages/rax-miniapp-runtime-webpack-plugin/src/index.js
=> refactor(miniapp): hot reload

packages/build-plugin-rax-app/src/loaders/MiniAppEntryLoader/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/element.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/root.js, packages/rax-miniapp-runtime-webpack-plugin/src/index.js
- feat(miniapp): export unmount method used in page unload event
- fix(miniapp): generate element file error for wechat
=> feat(miniapp): miniapp runtime project update

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/config/miniapp/runtime/getBase.js, packages/build-plugin-rax-app/src/loaders/MiniAppEntryLoader/index.js, packages/rax-miniapp-babel-plugins/package.json, packages/rax-miniapp-runtime-webpack-plugin/package.json, packages/rax-miniapp-runtime-webpack-plugin/src/generators/element.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/root.js, packages/rax-miniapp-runtime-webpack-plugin/src/index.js
=> [RELEASE] miniapp @0702

packages/postcss-plugin-rpx2vw/package.json, packages/postcss-plugin-rpx2vw/src/index.js
=> Fix: zero should return value with units

packages/rax-cli/bin/rax.js, packages/rax-cli/package.json
* Add Def tips
* Add Iceworks tips
=> Feat update create rax project cli text

packages/build-plugin-multi-demo-portal/package.json, packages/build-plugin-multi-demo-portal/src/config/portal.html
fix: visible area out of the demo box
fix: code box is too wide when it contains long string
=> fix(multi-demo-portal): fix demo style error

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/plugins/DocumentPlugin/index.js
should push html to each compilation assets
=> fix: document reload error

package.json, packages/build-plugin-rax-app/src/config/miniapp/runtime/getBase.js, packages/build-plugin-rax-app/src/config/miniapp/runtime/setEntry.js, packages/build-plugin-rax-app/src/loaders/MiniAppEntryLoader/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/app.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/config.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/page.js, packages/rax-miniapp-runtime-webpack-plugin/src/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/templates/app.js.ejs, packages/rax-miniapp-runtime-webpack-plugin/src/templates/page.js.ejs, packages/rax-miniapp-runtime-webpack-plugin/src/utils/wrapChunks.js
=> Revert "refactor(miniapp): use single file package mode render"

packages/build-plugin-rax-ssr/package.json, packages/build-plugin-rax-ssr/src/ssr/entryLoader.js, packages/build-plugin-rax-ssr/src/ssr/entryPlugin.js
=> feat: support assets processor

examples/rax-app-ts/README.md, examples/rax-app-ts/build.json, examples/rax-app-ts/package.json, examples/rax-app-ts/src/app.json, examples/rax-app-ts/src/app.ts, examples/rax-app-ts/src/components/LogoCss/index.css, examples/rax-app-ts/src/components/LogoCss/index.tsx, examples/rax-app-ts/src/components/LogoCssModule/index.module.css, examples/rax-app-ts/src/components/LogoCssModule/index.tsx, examples/rax-app-ts/src/components/LogoLess/index.less, examples/rax-app-ts/src/components/LogoLess/index.tsx, examples/rax-app-ts/src/components/LogoLessModule/index.module.less, examples/rax-app-ts/src/components/LogoLessModule/index.tsx, examples/rax-app-ts/src/components/LogoSass/index.scss, examples/rax-app-ts/src/components/LogoSass/index.tsx, examples/rax-app-ts/src/components/LogoSassModule/index.module.scss, examples/rax-app-ts/src/components/LogoSassModule/index.tsx, examples/rax-app-ts/src/document/index.jsx, examples/rax-app-ts/src/pages/Home/index.tsx, examples/rax-app-ts/src/typings.d.ts, examples/rax-app-ts/tsconfig.json, packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/config/user/keys/inlineStyle.js
=> feat: support css module

packages/rax-cli/bin/config.js, packages/rax-cli/bin/rax.js, packages/rax-cli/package.json
传递了 --templae 之后没有 answers.projectType，导致后面的逻辑分支出错。
=> fix: no appType

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/index.js, packages/build-plugin-rax-app/src/loaders/AppConfigLoader/getDepPath.js, packages/build-plugin-rax-app/src/loaders/AppConfigLoader/index.js, packages/rax-compile-config/src/platformLoader/TraverseImport.js, packages/rax-multi-pages-settings/package.json, packages/rax-multi-pages-settings/src/setConfig.js
=> feat: config multiple page auto render

packages/rax-cli/bin/rax.js, packages/rax-cli/package.json
=> feat remove init params console

packages/stylesheet-loader/package.json, packages/stylesheet-loader/src/index.js
=> fix: issue 427

packages/rax-cli/bin/rax.js, packages/rax-cli/package.json
update tips after create  `installed` to `added`, seem as ice
=> feat update tips after create

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/config/miniapp/compile/getBase.js
Support rax-app3.x miniapp compile project
=> feat: compatible with rax-app

packages/rax-cli/bin/config.js, packages/rax-cli/bin/rax.js, packages/rax-cli/package.json
- 支持跳过 cli 询问，可以通过 -s 或者 --skip-ask 跳过询问机制
- kraken 添加询问选择多页
- 当选择小程序为目标时，直接为 spa 应用
=> feat: support cli skip ask

packages/plugin-rax-app/src/config/options.config.js, packages/plugin-rax-app/src/index.js, packages/plugin-rax-app/src/setDev.js, packages/plugin-rax-app/src/utils/modifyTargets.js, packages/plugin-rax-pha/src/manifestHelpers.js, packages/plugin-rax-pha/src/plugins/AppToManifestPlugin.js, packages/plugin-rax-pha/src/setEntry.js, yarn.lock
支持 dev mode 指定需要调试的容器 https://github.com/raxjs/rax-app/issues/500
=> feat: support specified targets

CHANGELOG.md, packages/plugin-rax-web/package.json, packages/plugin-rax-web/src/DocumentPlugin/loader.ts, packages/rax-app/package.json
=> hotfix: rax-app 3.1.2

examples/with-rax/build.json, packages/plugin-rax-app/package.json, packages/plugin-rax-app/src/constants.js, packages/plugin-rax-app/src/index.js, packages/plugin-rax-app/src/setDev.js, packages/plugin-rax-app/src/utils/setDevUrlPrefix.js, packages/plugin-rax-pha/src/index.js, packages/plugin-rax-pha/src/plugins/AppToManifestPlugin.js
=> feat: support cloud IDE

packages/plugin-rax-compat-react/package.json, packages/plugin-ssr/index.d.ts, packages/plugin-ssr/src/index.ts
- 修复 ssr build 模式报错
- 更新 build-plugin-rax-compat-react 版本号
=> fix: ssr build

packages/plugin-rax-pha/src/plugins/AppToManifestPlugin.js, packages/plugin-rax-web/src/DocumentPlugin/index.ts, packages/plugin-rax-web/src/utils/document.ts, packages/plugin-rax-web/src/utils/htmlStructure.ts, packages/plugin-rax-web/src/utils/setRegisterMethod.ts, packages/plugin-ssr/src/ssr/entryPlugin.ts
使用方法：
在构建完成之后，
```js
const { applyMethod } = api;
// 优先使用 name 作为 entryName，custom 表示用户有没有通过 src/document 自定义 HTML
const { document, custom } = applyMethod('rax.getDocument', { name, source });
```
=>  feat: support get html content

packages/plugin-fusion-mobile/src/config/set-import.js, packages/plugin-rax-pha/src/__tests__/manifestHelper.js, packages/plugin-rax-pha/src/manifestHelpers.js
增加 name 的处理：
- 转成 key
- 生成 entryName
=> chore: handle entry name

packages/plugin-rax-pha/src/index.js, packages/plugin-rax-pha/src/plugins/AppToManifestPlugin.js, packages/plugin-rax-pha/src/setEntry.js, packages/plugin-rax-web/src/index.ts
没有 pha-worker.js 的时候不应该注册 pha 编译任务
=> fix: without pha-worker

packages/plugin-rax-pha/package.json, packages/plugin-rax-pha/src/__tests__/manifestHelper.js, packages/plugin-rax-pha/src/manifestHelpers.js, packages/plugin-rax-pha/src/plugins/AppToManifestPlugin.js, packages/rax-app/package.json
- 减少 def 插件代码，迁移到 pha plugin
- 增加单测
=> refactor: internal logic move to here

CHANGELOG.md, packages/plugin-ssr/package.json, packages/plugin-ssr/src/ssr/loaders/customDocumentLoader.ts, packages/rax-app/package.json, packages/rax-babel-config/package.json
- 添加更新日志
- 变更 rax-babel-config 版本号
- 修复 SSR 存在差异化渲染的时候，路径需要加引号
=> chore: release v3.2.5

.github/workflows/ci.yml
=> chore: change version check ci

packages/plugin-rax-store/src/generator.ts, packages/plugin-rax-store/src/index.ts, packages/plugin-rax-store/src/pageSourceLoader.ts, packages/plugin-rax-store/src/template/pageComponent.tsx.ejs, packages/plugin-rax-store/src/utils/checkStoreExists.ts, packages/plugin-rax-store/src/utils/getPath.ts, packages/plugin-rax-store/src/utils/modifyRoutes.ts, packages/plugin-rax-store/src/utils/modifyStaticConfigRoutes.ts
ref: https://github.com/alibaba/ice/pull/4023
=> fix: genreate tmp store file when no page store

packages/plugin-rax-app/src/setDev.js
=> fix: preserve previous build dir

packages/plugin-rax-app/package.json, packages/rax-app/package.json
=> chore: bump version

packages/plugin-rax-app/package.json, packages/plugin-ssr/package.json, packages/plugin-ssr/src/ssr/addPageHTMLAssign.ts, packages/rax-app-renderer/package.json, packages/rax-app-renderer/src/parseSearch.ts, packages/rax-app-renderer/src/renderer.tsx, packages/rax-app-renderer/src/server.tsx, packages/rax-app/package.json
=> fix: miniapp async render

packages/plugin-rax-web/src/setDev.ts
移除掉之前写死的逻辑，支持多页应用 browser history
=> feat: browser history in MPA

packages/plugin-rax-pha/src/__tests__/manifestHelper.js, packages/plugin-rax-pha/src/manifestHelpers.js
dataPrefetches header 和 data 不转化，功能见单测
=> fix: data prefetches do not decamelize

packages/build-plugin-rax-miniapp-plugin/package.json, packages/build-plugin-rax-miniapp-plugin/src/config/getBase.js, packages/build-plugin-rax-miniapp-plugin/src/plugins/miniapp/ModifyOutputFileSystem.js, packages/build-plugin-rax-miniapp-plugin/src/plugins/miniapp/RemoveDefaultResult.js
=> feat(miniapp-plugin): support miniapp-native dir copy in plugin project

CHANGELOG.md, packages/plugin-rax-web/CHANELOG.md, packages/plugin-rax-web/package.json, packages/plugin-rax-web/src/Plugins/DocumentPlugin.ts, packages/plugin-rax-web/src/setLocalBuilder.ts, packages/rax-app/package.json
在 Weex 类型应用里，DEF 插件会给 `DocumentPlugin` 增量添加两个参数修改构建结果
=> fix: receive params passed by DEF plugin

packages/plugin-rax-pha/src/__tests__/manifestHelper.js, packages/plugin-rax-pha/src/manifestHelpers.js
- 增加更多的白名单
- 兼容数据预请求格式，避免安卓 crash
=> feat: add white list for manifest and android crash

packages/plugin-rax-app/src/postcss.config.js
https://github.com/alibaba/rax/issues/2082
=> fix: imported css rpx unit converted fail

packages/plugin-ssr/src/ssr/EntryLoader.ts, packages/plugin-ssr/src/ssr/addBuiltInRenderComponentToHTML.ts, packages/plugin-ssr/src/ssr/addCustomRenderComponentToHTML.ts, packages/plugin-ssr/src/ssr/entryPlugin.ts, packages/plugin-ssr/src/types.ts
Add flag to control whether inject initial data into html
=> feat: add injectServerSideData in app.json

packages/plugin-ssr/src/ssr/EntryLoader.ts
SSR `getInitailProps` 返回的数据类型需要兼容 `null`
=> fix: ssr initial props can be null

packages/plugin-rax-pha/src/__tests__/manifestHelper.js, packages/plugin-rax-pha/src/manifestHelpers.js
- dataPrefetches => dataPrefetch prefetch 是抽象名字，不应该有复数
- 之前客户端字段有变动，字段名不改里面的字段有变动会引起老版本 crash，趁着改造就一起改了
=> chore: change data prefetch key

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/build.js, packages/build-plugin-rax-app/src/dev.js, packages/build-plugin-rax-app/src/index.js, packages/build-plugin-rax-app/src/tip.js
build-plugin-rax-app @5.x
构建启动前和结束后均添加提示
=> chore: plugin 5.x add upgrade tip

packages/build-plugin-rax-app/package.json, packages/build-plugin-rax-app/src/build.js, packages/build-plugin-rax-app/src/dev.js, packages/build-plugin-rax-app/src/index.js, packages/build-plugin-rax-app/src/tip.js
build-plugin-rax-app @4.x 增加升级提示
=> chore: plugin 4.x add upgrade tip

examples/miniapp-subpackages/package.json, examples/miniapp-subpackages/src/miniapp-native/common/test.js, examples/miniapp-subpackages/src/pages/About/module/index.jsx, examples/miniapp-subpackages/src/pages/Home/module/index.jsx, packages/plugin-rax-miniapp/src/index.js
支持微信小程序分包 `src/miniapp-native/shared` 目录下的 JS 文件共享运行时内存
=> feat: support share memory with subpackages

examples/with-rax-pha/build.json, examples/with-rax-pha/src/app.json, examples/with-rax-pha/src/document/index.jsx, packages/plugin-rax-pha/src/plugins/AppToManifestPlugin.js, packages/plugin-rax-web/src/Plugins/DocumentPlugin.ts
Support config source in `tabBar`:
```json
{
"tabBar": {
"source": "pages/TabBar/index"
}
}
```
=> feat: support build tabbar html

packages/plugin-rax-app/src/setDev.js
=> chore: remove print local url in console

packages/plugin-ssr/src/ssr/EntryLoader.ts, packages/plugin-ssr/src/ssr/addBuiltInRenderComponentToHTML.ts, packages/plugin-ssr/src/ssr/addCustomRenderComponentToHTML.ts, packages/plugin-ssr/src/ssr/entryPlugin.ts, packages/plugin-ssr/src/types.ts
build.json
```json
{
"web": {
"ssr": { "updateDataInClient": true }
}
}
```
=> chore: use updateDataInClient

packages/plugin-rax-web/package.json, packages/plugin-rax-web/src/Plugins/DocumentPlugin.ts
避免 cheerio 在处理 xtpl 的时候格式化 HTML 文件
=> fix: csr html structure error with xtpl

packages/plugin-rax-pha/src/plugins/AppToManifestPlugin.js
将 page 里的 dataPrefetch 取出放到根上，这样就可以在每个页面上定义不同的 dataPrefetch
=> feat: take data prefetch of page and assign it to the root

packages/plugin-rax-web/src/Loaders/hmr-loader.ts, packages/plugin-rax-web/src/index.ts, packages/rax-app-renderer/src/renderer.tsx
=> chore: change page reload for partial update

examples/basic-spa-ssr/src/app.json, packages/plugin-rax-web/package.json, packages/plugin-ssr/src/ssr/EntryLoader.ts, packages/plugin-ssr/src/ssr/addPageHTMLAssign.ts, packages/rax-app-renderer/package.json, packages/rax-app-renderer/src/renderer.tsx
1. 根据开发者的配置选择性注入 TabBar，无 TabBar 场景压缩情况下 bundle 体积减少 4kb
2. 复用 MPA 内置 TabBar
=> refactor: conditional inject SPA TabBar

CHANGELOG.md, examples/force-enable-css/build.json, examples/force-enable-css/src/global.scss, examples/force-enable-css/src/pages/Home/index.module.css, examples/force-enable-css/src/pages/Home/index.tsx, packages/babel-plugin-transform-jsx-stylesheet/src/index.ts, packages/plugin-rax-app/src/userConfig/inlineStyle.js, packages/plugin-rax-store/CHANGELOG.md, packages/plugin-rax-store/package.json, packages/plugin-rax-store/src/utils/checkExpectedStoreFileExists.ts, packages/plugin-rax-store/src/utils/getPath.ts, packages/plugin-rax-store/src/utils/modifyRoutes.ts, packages/rax-app/package.json
=> hotfix: rax-app v3.6.4

packages/babel-plugin-track-id-generator/package.json, packages/babel-plugin-transform-jsx-stylesheet/package.json, packages/babel-plugin-transform-jsx-to-html/package.json, packages/build-html-generator/package.json, packages/codemod/package.json, packages/compat-webpack4/package.json, packages/error-stack-tracey/package.json, packages/exports-field-webpack-plugin/package.json, packages/platform-loader/package.json, packages/plugin-fusion-mobile/package.json, packages/plugin-midway-faas/package.json, packages/plugin-rax-api-builder/package.json, packages/plugin-rax-app/package.json, packages/plugin-rax-compat-react/package.json, packages/plugin-rax-faas/package.json, packages/plugin-rax-fc/package.json, packages/plugin-rax-kraken/package.json, packages/plugin-rax-miniapp/package.json, packages/plugin-rax-now/package.json, packages/plugin-rax-pha/package.json, packages/plugin-rax-router/package.json, packages/plugin-rax-store/package.json, packages/plugin-ssr/package.json, packages/rax-app-renderer/package.json, packages/rax-babel-config/package.json, packages/rax-jest-config/package.json, packages/rax-webpack-config/package.json, packages/stylesheet-loader/package.json
=> chore: format publish result

packages/rax-app/package.json
=> chore: add minimum node version

packages/plugin-rax-pha/CHANELOG.md, packages/plugin-rax-pha/package.json, packages/plugin-rax-pha/src/__tests__/manifestHelper.js, packages/plugin-rax-pha/src/manifestHelpers.js, packages/plugin-rax-pha/src/plugins/AppToManifestPlugin.js
根据产物确定是否要在 pha 中增加 script or stylesheet
=> fix: inject script or stylesheet by assets

packages/plugin-rax-app/src/base.js
https://github.com/alibaba/ice/pull/4895
=> fix: swc compile

packages/plugin-rax-web/src/Loaders/render-loader.ts, packages/plugin-rax-web/src/Plugins/DocumentPlugin.ts, packages/plugin-rax-web/src/setLocalBuilder.ts
=> fix: static exports error

packages/plugin-rax-app/src/base.js
https://github.com/microsoft/tslib/issues/161
=> fix: tslib error

examples/with-rax-mpa/src/components/Logo/index.tsx, packages/plugin-rax-app/src/global/setStaticConfig.js, packages/plugin-rax-app/src/userConfig/modify.ts, packages/plugin-rax-app/src/userConfig/register.ts
原因: https://github.com/alibaba/ice/issues/4956
通过区分应用类型可以先绕过这个问题
=> fix: mpa tabbar render

packages/plugin-rax-app/package.json
webpack4: `node-libs-browser`
webpack5: `process`/`events`
=> chore: add webpack deps

packages/plugin-rax-router/src/runtime.tsx, packages/plugin-rax-router/src/runtime/TabBar.tsx
修复路由切换时，tabbar active item 未切换的问题
=> fix: tabbar toggle error

__tests__/build-cases/basic-spa.test.ts, __tests__/dev-cases/with-rax-mpa.test.ts, examples/basic-mpa-webpack5/build.json, examples/basic-spa-ssr/build.json, examples/basic-spa/src/app.tsx, examples/with-atomic-css/build.json, examples/with-rax-mpa/build.json, packages/plugin-rax-app/src/config/user.config.ts, packages/plugin-rax-app/src/constants.js, packages/plugin-rax-app/src/global/index.ts, packages/plugin-rax-app/src/global/setDevUrlPrefix.ts, packages/plugin-rax-app/src/runtime.tsx, packages/plugin-rax-router/src/runtime.tsx, packages/plugin-ssr/src/ssr/EntryLoader.ts, packages/plugin-ssr/src/ssr/addPageHTMLAssign.ts, packages/rax-app-renderer/src/renderer.tsx, packages/rax-app-renderer/src/server.tsx
1. 修复 `Page.getInitialProps` 在 CSR 未执行的问题
2. `getInitialProps` 入参 `ctx` 新增返回 `pathname`/`location`
3. https 签发 ip 地址改为通过全局 list 注册的方式 https://github.com/alibaba/ice/pull/5011
=> fix: ssr getInitialProps

packages/plugin-ssr/CHANGELOG.md, packages/plugin-ssr/package.json, packages/plugin-ssr/src/index.ts, packages/plugin-ssr/src/ssr/EntryLoader.ts, packages/plugin-ssr/src/ssr/addBuiltInRenderComponentToHTML.ts, packages/plugin-ssr/src/ssr/addCustomRenderComponentToHTML.ts, packages/plugin-ssr/src/ssr/entryPlugin.ts, packages/plugin-ssr/src/ssr/setDev.ts, packages/plugin-ssr/src/utils/formatEntryLoaderQuery.ts, packages/plugin-ssr/src/utils/injectBundleInfo.ts, packages/rax-app/package.json, packages/rax-webpack-config/CHANELOG.md, packages/rax-webpack-config/package.json
=> Revert "fix: FaaS error case"

CHANGELOG.md, packages/plugin-rax-web/CHANGELOG.md, packages/plugin-rax-web/package.json, packages/plugin-rax-web/src/Plugins/DocumentPlugin.ts, packages/plugin-rax-web/src/index.ts, packages/plugin-ssr/CHANGELOG.md, packages/plugin-ssr/package.json, packages/plugin-ssr/src/ssr/EntryLoader.ts, packages/rax-app/package.json
=> Revert "fix(plugin-rax-web): not filter routes by target in document plugin"

packages/create-rax/CHANGELOG.md, packages/create-rax/bin/create.js, packages/create-rax/package.json
https://github.com/cnpm/cnpm/issues/361?spm=defwork.home.0.0.72ce3f1bz8qwmn
=> chore: change taobao registry url

CHANGELOG.md, packages/rax-webpack-config/CHANELOG.md, packages/rax-webpack-config/package.json, packages/rax-webpack-config/src/setWebpackLoaders.ts
https://github.com/webpack-contrib/css-loader#features
=> fix: css modules global selector

CHANGELOG.md, packages/plugin-rax-app/CHANGELOG.md, packages/plugin-rax-app/package.json, packages/plugin-rax-app/src/userConfig/atoms/inlineStyle.js, packages/rax-app/package.json, packages/rax-webpack-config/CHANELOG.md, packages/rax-webpack-config/package.json
- Feat: breaking change for `@builder/rax-pack` to update `postcss-loader`
- Feat: breaking change for `rax-webpack-config` to update `postcss-loader`
=> feat: update postcss-loader

package.json, packages/rax-babel-config/CHANGELOG.md, packages/rax-babel-config/package.json, packages/rax-babel-config/src/index.js
官方已经修复这个问题 https://github.com/babel/minify/issues/981 不再需要 fork 版本
=> chore: use official babel minify plugin

packages/plugin-rax-app/package.json, packages/plugin-rax-app/src/launch/setupTest.ts, packages/rax-app/package.json
=> fix: rax-app test failed

packages/postcss-plugin-rpx2vw/CHANGELOG.md, packages/postcss-plugin-rpx2vw/package.json, packages/postcss-plugin-rpx2vw/src/index.js
migrate `postcss-plugin-rpx2vw` for postcss 8.x
=> feat: plugin migrate to postcss 8.x

packages/rax-webpack-config/CHANELOG.md, packages/rax-webpack-config/package.json, packages/rax-webpack-config/src/setWebpackLoaders.ts
=> fix: support mjs/cjs/mts
