raxjs/rax-app

- packages/rax-plugin-ssr/package.json
- packages/rax-plugin-ssr/src/ssr/setDev.js
修复 ssr 应用，默认的 dev server 报错。
由于 bundleContent 默认暴露的是一个 render 方法：
```
export {
render,
renderToHTML
};
export default render;
```
所以通过原有方式去调用 render 方法，会出现报错。
> fix: dev server

- packages/rax-plugin-ssr/package.json
- packages/rax-plugin-ssr/src/ssr/getBase.js
- packages/rax-template/package.json
- packages/rax-template/template/scaffold/package.json.ejs
- packages/rax-template/template/scaffold/src/document/index.jsx.ejs
1. SSR 工程默认引入 babel-plugin-transform-jsx-to-html  插件，进行预编译 JSX 
2. Document 中，修复 script 标签闭合，JS 未被执行的问题
> feat: transfor jsx to html

- packages/rax-plugin-app/package.json
- packages/rax-plugin-app/src/plugins/PWAAppShellPlugin.js
rax-compile-config platformLoader will translate universal-env
@example isWeb=true 
before:
import { isWeb, isWeex } from 'universal-env';
after:
const isWeb = true;
const isWeex = false
App shell will be rendered with Node.js, Some code in wrong environment will throw error.
Find platformLoader 'web' env and translate to the right environment 'node'
> fix: app shell plugin use wrong platformLoader env

- packages/build-plugin-rax-app/package.json
- packages/build-plugin-rax-app/src/config/user/keys/devServer.js
- packages/build-plugin-rax-component/package.json
- packages/build-plugin-rax-component/src/config/user/default.config.js
- packages/build-plugin-rax-component/src/config/user/keys/devServer.js
为了能够使用 localhost、127.0.0.1 启动本地调试服务，把默认的 ip 配置去掉。
默认使用 0.0.0.0 同时支持 localhost、127.0.0.1 以及 ip 方案
> feat: use default host localhost for dev

- packages/build-plugin-rax-app/package.json
- packages/build-plugin-rax-app/src/dev.js
- packages/build-plugin-rax-component/package.json
- packages/build-plugin-rax-component/src/dev.js
We use Weex App to scan QRCode debug Weex page.
Mobile phone can't visit url like http://localhost:3333/weex/index.js?wh_weex=true.
Change http://localhost:3333/weex/index.js?wh_weex=true to http://xx.xx.xx.xx:3333/weex/index.js?wh_weex=true
> Feat use 'IP address' instead of 'localhost' in Weex App

- packages/build-plugin-rax-app/package.json
- packages/build-plugin-rax-app/src/plugins/UniversalDocumentPlugin.js
- packages/build-plugin-rax-multi-pages/src/index.js
- packages/rax-generator/package.json
- packages/rax-generator/src/template/app/src/components/Logo/index.jsx.ejs
- packages/rax-generator/src/template/app/src/pages/Home/index.jsx.ejs
仅在构建产物有 css 文件的时候，向 document 透出 style 路径
> fix: return styles when there is styles in webpack output

- packages/build-plugin-rax-component/package.json
- packages/build-plugin-rax-component/src/config/user/keys/publicPath.js
- packages/build-plugin-rax-component/src/config/web/getDev.js
changes: 
1. fix  config  confict of html-webpack-plugin when there are multiple demos
2. set defaultPublicPath as `./`, in order to generate preview pages (no other effect)
> fix: build rax component demo page

- packages/build-plugin-rax-multi-pages/package.json
由于之前有 build-plugin-mulit-pages 的部分改动没有发布版本，https://github.com/raxjs/rax-scripts/pull/152 顺带发布了之前的提交，涉及到 document 改动的 breakchange，所以升级大版本
回滚方案
https://github.com/raxjs/rax-scripts/pull/152 发布的 0.1.5 已经回滚、tnpm 已同步
影响范围
0.1.5 版本会对 "build-plugin-rax-app": "^0.1.0" 的老业务产生影响，用户需要手动修改并升级 document
对最新创建的工程无影响
> Feat update multi pages version

- packages/build-plugin-rax-app/package.json
- packages/build-plugin-rax-app/src/config/miniapp/runtime/getBase.js
- packages/rax-compile-config/package.json
- packages/rax-compile-config/src/getBabelConfig.js
小程序运行时方案沿用了默认的 babel 编译配置，会引入 regenerator-runtime 用于处理 async/await 函数。但是 regenerator-runtime 中使用的 `new Function(...)` 语法出于安全问题在小程序框架中被禁用，同时小程序目前已支持 async/await，无需引入 polyfill。因此增加配置用于关闭 @babel/plugin-transform-runtime 中 regenerator 设置。
> feat(miniapp): support disable regenerator in babel config

- packages/build-plugin-rax-app/package.json
- packages/build-plugin-rax-app/src/build.js
- packages/build-plugin-rax-app/src/config/processRelativePublicPath.js
- packages/build-plugin-rax-app/src/config/user/keys/inlineStyle.js
- packages/build-plugin-rax-app/src/plugins/UniversalDocumentPlugin.js
- packages/build-plugin-rax-multi-pages/package.json
Support publicPath use relative path.
For example:
Set publicPath './', make Web App serving the same build from different paths.
It will make all the asset paths are relative to index.html.
User can be able to move their app anywhere without having to rebuild it.
```json
{
"publicPath": "./"
}
```
> Feat support publicPath use relative path

- packages/build-plugin-rax-component/package.json
- packages/build-plugin-rax-component/src/buildLib.js
- fix: gulpCompile is invoked twice when using typescript
- fix: can't find src/index.js when target only contains miniapp
> fix(plugin-rax-component): build lib when targets contain miniapp

- packages/jsx2mp-cli/getWebpackConfig.js
- packages/jsx2mp-cli/package.json
use user-passed `workDirectory` parameter
1. workDirectory has been used to represent current working directory which can be changed by situation
2. current working directory not always be `process.cwd()`, for example, as a test case in `<project>/test/fixtures`
> fix(jsx2mp-cli): use `workDirectory` instead of `process.cwd()`

- packages/jsx2mp-loader/src/babel-plugin-rename-import.js
- fix the path error like the following:
```js
var legacyMap = require("entities/maps/legacy.json");
```
Since json file wille be tranformed to js file, hence the require path should change.
Wrong: 
```js
var legacyMap = require("../../_entities_1.1.2_entities/maps/legacy.json");
```
Correct: 
```js
var legacyMap = require("../../_entities_1.1.2_entities/maps/legacy");
```
> fix(jsx2mp): path error when requiring npm json file

- packages/build-plugin-rax-component/package.json
- packages/build-plugin-rax-component/src/config/node/getDev.js
原有方式引入了换行符，Client hydrate 的时候会拿正常节点与换行符进行比对，导致错误
> fix: extra text node in ssr

- packages/build-plugin-rax-app/package.json
- packages/build-plugin-rax-app/src/config/miniapp/runtime/getBase.js
- packages/rax-miniapp-babel-plugins/package.json
- packages/rax-miniapp-babel-plugins/src/plugins/babel-plugin-native-lifecycle.js
- packages/rax-miniapp-babel-plugins/src/utils/getPagePath.js
由于 babel plugin 的并行机制，预编译直接使用 babel plugins 的方式会导致，假如用户通过自定义 babel plugin 修改文件，miniapp babel plugins 拿到的还是用户修改前的源文件，从而影响了用户的定制能力。
> feat: use miniapp babel presets insteadof babel plugins

- packages/rax-miniapp-runtime-webpack-plugin/package.json
- packages/rax-miniapp-runtime-webpack-plugin/src/generators/custom-component.js
- packages/rax-miniapp-runtime-webpack-plugin/src/templates/ali-miniapp/custom-component.js.ejs
- packages/rax-miniapp-runtime-webpack-plugin/src/templates/wechat-miniprogram/custom-component.js.ejs
渲染原生自定义组件时，需要在父层构造的 `custom-component` `didMount` 时，读取开发者使用到的 `props`，再通过 `setData` 传递给目标组件，这会导致目标组件第一次渲染时拿不到 `props`。
父层组件通过 `ready` 控制目标组件渲染，使目标组件初次渲染和获取 `props` 是同步行为。
> feat(miniapp): add render control to custom component

- packages/rax-miniapp-runtime-webpack-plugin/src/generators/element.js
- packages/rax-miniapp-runtime-webpack-plugin/src/generators/page.js
- packages/rax-miniapp-runtime-webpack-plugin/src/index.js
页面根节点通过自定义组件渲染，从而避免在使用到原生组件时，将 root.axml 每次都写入每个页面造成小程序体积过大
> chore(miniapp): root node use custom component

- packages/build-plugin-rax-app/src/config/miniapp/filterNativePages.js
- packages/build-plugin-rax-app/src/config/miniapp/runtime/getBase.js
- packages/rax-miniapp-runtime-webpack-plugin/src/index.js
`build` 模式下，原生页面的复制操作是在 webpack 清空 `build` 目录之前执行的，导致产物中原生页面丢失
> fix(miniapp): native page copy

- packages/build-plugin-rax-app/package.json
- packages/build-plugin-rax-app/src/config/user/keys/stats.js
- packages/build-plugin-rax-app/src/plugins/DocumentPlugin/index.js
- packages/build-plugin-rax-ssr/package.json
- packages/build-plugin-rax-ssr/src/ssr/setDev.js
- packages/error-stack-tracey/package.json
- packages/error-stack-tracey/src/index.js
1. 修复本地 dev 阶段内存泄漏问题
2. 错误日志结构化兼容无 sourcemap 的情况
3. 修复 stats 没有正常关闭的问题
约 50 次修改后，内存的占用情况对比
修改前
修改后
原因为渲染 Document，使用了 Webpack 构建过程中的产物，会导致内存无法释放。修复方式：先减少不必要的渲染逻辑，后续考虑 Document 不走 Webpack 构建。
> Fix memory leak when render document

- packages/rax-miniapp-config-webpack-plugin/package.json
- packages/rax-miniapp-config-webpack-plugin/src/index.js
> fix(miniapp): config in disorder

- packages/build-plugin-rax-app/src/index.js
- build-plugin-rax-app 插件默认做了 enterCheck 检查，即要求在 build.json 中配置顺序为第一个，在 raxjs 中将会内置 build-plugin-rax-app 插件，在这种场景下不需要开启检查，因此新增 enterCheck 参数用于配置
> feat: support ignore plugin check

- packages/build-plugin-rax-app/package.json
- packages/build-plugin-rax-app/src/config/miniapp/runtime/getBase.js
- packages/build-plugin-rax-app/src/config/pathHelper.js
- packages/rax-webpack-config/package.json
- packages/rax-webpack-config/src/index.js
> fix(build-plugin-rax-app):rax-app project error

- packages/rax-compile-config/package.json
- packages/rax-compile-config/src/hmr/webpackHotDevClient.entry.js
支持通过 `process.env.SOCK_PORT`/`process.env.SOCK_PATH`/`process.env.SOCK_PROTOCOL` 设置 sock 配置
> feat: support set sock info

- packages/build-plugin-rax-app/package.json
- packages/build-plugin-rax-app/src/config/miniapp/compile/getBase.js
止血操作，小程序编译时会在编译时替换 rax-app，无需经过 webpack 依赖分析
> fix: rax-app resolve fail

- packages/build-plugin-rax-app/src/config/miniapp/runtime/getBase.js
- packages/rax-miniapp-babel-plugins/src/index.js
- packages/rax-miniapp-babel-plugins/src/plugins/babel-plugin-handle-native-component.js
> feat(miniapp): add runtimeDependencies to control runtime components use

- packages/build-plugin-rax-app/package.json
- packages/build-plugin-rax-app/src/index.js
- packages/rax-multi-pages-settings/package.json
- packages/rax-multi-pages-settings/src/setConfig.js
build-plugin-rax-app@5.2.3-0
```diff
{
"routes": [
{
"path": "home",
"source": "pages/home/index",
+      "autoRender": false  // default true
},
{
"path": "home-pc",
"source": "pages/home/index-pc"
}
],
"hydrate": true
}
```
加了这个选项之后，MPA 情况下工程不会自动包 render()，render 逻辑业务自己负责：
```js
import { createElement, render } from 'rax';
import Driver from 'universal-driver';
const Home = () => {
return <>home</>;
}
render(<Home />, document.getElementById('root'), {
driver: Driver
});
```
> chore: mpa support autoRender option

- packages/rax-miniapp-babel-plugins/package.json
- packages/rax-miniapp-babel-plugins/src/plugins/babel-plugin-remove-Function.js
- packages/rax-miniapp-babel-plugins/src/utils/handleComponentAST.js
- 解决 babel 插件在移除相关节点时冲突的操作
- 原生自定义组件和插件添加 `__native` 属性作为区分
> fix: regeneratorRuntime path remove error

- packages/build-plugin-rax-app/package.json
- packages/build-plugin-rax-app/src/config/getWebpackBase.js
- packages/build-plugin-rax-app/src/config/user/keys/inlineStyle.js
- 修复小程序生成多余的 `public` 文件夹
- 修复 `inlineStyle: false` 的情况下，通过 `npm` 包的形式引入多个 `css` 文件报错的问题
> fix: inlineStyle false add wrong babel plugin

- .github/workflows/beta-publisher.yml
- .github/workflows/ci.yml
- README.md
- README_zh-CN.md
- examples/with-rax-miniapp-compile/README.md
- examples/with-rax-mpa/README.md
- examples/with-rax-store/README.md
- examples/with-rax-style/README.md
- examples/with-rax-style/build.json
- examples/with-rax-style/package.json
- examples/with-rax-style/src/app.json
- examples/with-rax-style/src/app.ts
- examples/with-rax-style/src/components/LogoCss/index.css
- examples/with-rax-style/src/components/LogoCss/index.tsx
- examples/with-rax-style/src/components/LogoCssModule/index.module.css
- examples/with-rax-style/src/components/LogoCssModule/index.tsx
- examples/with-rax-style/src/components/LogoLess/index.less
- examples/with-rax-style/src/components/LogoLess/index.tsx
- examples/with-rax-style/src/components/LogoLessModule/index.module.less
- examples/with-rax-style/src/components/LogoLessModule/index.tsx
- examples/with-rax-style/src/components/LogoSass/index.scss
- examples/with-rax-style/src/components/LogoSass/index.tsx
- examples/with-rax-style/src/components/LogoSassModule/index.module.scss
- examples/with-rax-style/src/components/LogoSassModule/index.tsx
- examples/with-rax-style/src/document/index.jsx
- examples/with-rax-style/src/pages/Home/index.tsx
- examples/with-rax-style/src/typings.d.ts
- examples/with-rax-style/tsconfig.json
- examples/with-rax/README.md
- packages/rax-babel-config/package.json
脚手架默认 inlineStyle 改为 false 之后，用 css 冲突概率很大，因此希望统一成 CSS Module，但是如果开发者把 inlineStyle 改为 true 就报错了，因此 babel-plugin-transform-jsx-stylesheet@1.0 支持了 inlineStyle+CSS Module https://github.com/raxjs/rax-scripts/pull/424 
```diff
- import './index.css';
+ import styles from './index.module.css';
- <div className="logo" />
+ <div className={styles.logo} />  
```
- rax-materials 脚手架默认改为 CSS Module 写法
> feat: rax-app support css modules

- .github/workflows/ci.yml
- examples/custom-output-dir/README.md
- examples/custom-output-dir/build.json
- examples/custom-output-dir/package.json
- examples/custom-output-dir/src/app.json
- examples/custom-output-dir/src/app.tsx
- examples/custom-output-dir/src/components/BuggyCounter/index.tsx
- examples/custom-output-dir/src/components/Logo/index.css
- examples/custom-output-dir/src/components/Logo/index.tsx
- examples/custom-output-dir/src/document/index.jsx
- examples/custom-output-dir/src/pages/About/index.css
- examples/custom-output-dir/src/pages/About/index.tsx
- examples/custom-output-dir/src/pages/Home/index.css
- examples/custom-output-dir/src/pages/Home/index.tsx
- examples/custom-output-dir/tsconfig.json
- packages/plugin-rax-app/src/config/options.config.js
- packages/plugin-rax-app/src/config/user.config.js
- packages/plugin-rax-app/src/index.js
- packages/plugin-rax-app/src/setBuild.js
- packages/plugin-rax-app/src/setDev.js
- packages/plugin-rax-miniapp/src/index.js
> fix: custom output dir

- examples/basic-split-chunk/README.md
- examples/basic-split-chunk/build.json
- examples/basic-split-chunk/package.json
- examples/basic-split-chunk/src/app.json
- examples/basic-split-chunk/src/app.ts
- examples/basic-split-chunk/src/components/Logo/index.css
- examples/basic-split-chunk/src/components/Logo/index.tsx
- examples/basic-split-chunk/src/document/index.tsx
- examples/basic-split-chunk/src/pages/About/index.module.css
- examples/basic-split-chunk/src/pages/About/index.tsx
- examples/basic-split-chunk/src/pages/Home/index.module.css
- examples/basic-split-chunk/src/pages/Home/index.tsx
- examples/basic-split-chunk/tsconfig.json
- packages/plugin-rax-app/src/config/user.config.js
- packages/plugin-rax-app/src/userConfig/vendor.js
- packages/plugin-rax-web/src/index.js
- 修复 document 插件通过 `webpackChainConfig.toConfig` 获取 webpack 配置时，修改了 web 主流程任务配置引用的问题
- 修复 dynamic import 生成 vendor 公共文件时，由于没有强制抽离公共文件，导致 A 页面的公共样式未抽离，A 页面跳转到 B 页面，再返回 A 页面时，B 页面样式污染 A 页面的问题
> fix: chunk load

- packages/plugin-rax-app/src/config/user.config.js
- packages/rax-app-renderer/src/renderer.tsx
- packages/rax-webpack-config/src/webpack.build.js
- `compileDependencies` 默认值改为 `[]`，在目前 node_modules 分端代码移除没生效的情况下，考虑编译速度，默认值应该是 `[]`
- 支持配置 `hydrate: true`
- TerserPlugin 配置默认改为移除未使用到的代码
> chore: change config

- packages/rax-babel-config/src/index.js
`disableRegenerator` 只是在小程序中不注入 regenerate-runtime 依赖，babel 依然需要在小程序中转换 generator 语法糖，避免微信报错
> fix: babel need transform generator syntactic sugar

- packages/plugin-rax-web/src/__tests__/htmlStructure.test.ts
- packages/plugin-rax-web/src/utils/htmlStructure.ts
cheerio 会 format 不符合规范的 html 结构，在移除 cheerio 之后暴露拼装 HTML 不合规范的问题
> fix: generate html when insert extra scripts

- examples/miniapp-subpackages/package.json
- examples/miniapp-subpackages/src/pages/Home/module/index.jsx
- packages/plugin-rax-miniapp/src/index.js
小程序分包模式抽离所有分包公共代码到主包，有效降低分包代码体积
以[简单示例代码](https://github.com/raxjs/rax-app/blob/master/examples/miniapp-subpackages/README.md)为例，压缩后代码从 378kb 下降到 216kb
> chore: reduce miniapp size with subPackages

- packages/plugin-rax-miniapp/src/index.js
运行时项目中，使用编译时组件（miniapp-compiled目录），目录下无法生成npm目录。排查源码后发现，是disableCopyNpm属性在rax-app-->plugin-rax-miniapp下写死为true。PR建议：是否生成npm目录，交给用户配置。
> fix: 运行时项目中，编译时组件目录下，是否拷贝npm目录，配置化。

- CHANGELOG.md
- packages/plugin-rax-miniapp/CHANGELOG.md
- packages/plugin-rax-miniapp/package.json
- packages/plugin-rax-miniapp/src/index.js
- packages/rax-app/package.json
`vendor` test 的参数返回是一个对象，其中的 `context` 属性是文件的绝对路径
> fix: miniapp vendor test

- packages/codemod/CHANELOG.md
- packages/codemod/package.json
- packages/codemod/src/transforms/app/app.json.ts
旧工程 route 中存在 name 时，需要给 name 添加 `pages/`，保证输出目录一致
> chore : optimize handle route name

- packages/build-plugin-rax-miniapp-plugin/src/config/getBase.js
- packages/build-plugin-rax-miniapp-plugin/src/plugins/miniapp/CopyBuildResult.js
- packages/jsx2mp-cli/__tests__/component.js
- packages/jsx2mp-cli/plugins/runtime.js
> feat(miniapp): copy build result to demo folder

- CHANGELOG.md
- packages/plugin-ssr/CHANELOG.md
- packages/plugin-ssr/package.json
- packages/plugin-ssr/src/ssr/EntryLoader.ts
- packages/plugin-ssr/src/ssr/addCustomRenderComponentToHTML.ts
- packages/plugin-ssr/src/ssr/addPageHTMLAssign.ts
- packages/plugin-ssr/src/types.ts
- packages/plugin-ssr/src/utils/getPageConfig.ts
- packages/rax-app-renderer/CHANGELOG.md
- packages/rax-app-renderer/package.json
- packages/rax-app-renderer/src/renderer.tsx
- packages/rax-app-renderer/src/server.tsx
- packages/rax-app/package.json
- Feat: support pass `props.pageConfig` to page component
- Feat: throw error when not using the BrowserRouter
- Chore: `errorBoundary` default value changed to `true`
> release: v3.5.1

- packages/plugin-ssr/src/ssr/setDev.ts
1. 通过 compiler.options.output.path 生成文件路径，避免 output path 被其他插件修改，导致的"找不到文件"问题
2. 从 compiler.outputFileSystem 读取文件代码会更健壮，不依赖 writeToDisk: true
closes #735
> fix: read file content from compiler memfs

- packages/plugin-rax-app/src/index.js
- packages/plugin-rax-app/src/utils/setDevUrlPrefix.js
```json
{
"devServer": {
"host": "m.taobao.com"
}
}
```
修复配置了 devServer host 后，命令行依旧打印 ip 地址作为调试链接的问题
> fix: console dev url

- packages/rax-app-renderer/src/renderer.tsx
默认应该关闭 errorBoundary，莫名的 JS 报错出现的兜底组件对业务是有干扰的
> chore: change errorBoundary default value

- examples/basic-mpa-with-document/src/document/index.jsx
- packages/plugin-rax-web/package.json
- packages/plugin-rax-web/src/Plugins/DocumentPlugin.ts
- packages/rax-app/package.json
In the previous version, if an error was reported during document construction, the construction task would not be interrupted.
Now fixed it.
> fix: throw document build error

- packages/plugin-rax-web/src/setLocalBuilder.ts
Before this PR, files in `src/document` can not trigger rebuild, this bug is fixed in this PR.
> fix: document live load

- packages/plugin-rax-app/src/Loaders/RouteLoader.ts
小程序页面组件不能直接引入，会导致页面和渲染无关的代码在 app onlaunch 阶段执行，导致 `getApp()` 返回 `undefined`
> chore: avoid excute page code directly

- packages/plugin-rax-app/src/Loaders/RouteLoader.ts
- packages/rax-app/src/index.ts
- Avoid error when `route.path` with `-`, like: `/list-a`
- SSR plugin order
> fix: some edge cases

- packages/rax-webpack-config/CHANELOG.md
- packages/rax-webpack-config/package.json
- packages/rax-webpack-config/src/webpack.build.ts
TerserPlugin `sourceMap` 不应该强制指定，插件内部默认的行为更加合理，即根据 `webpackConfig.devtool` 的值决定是否生成 `sourceMap`
> chore: terser plugin sourceMap  default value is depended on webpackConfig.devtool

- packages/plugin-rax-app/package.json
- packages/plugin-rax-app/src/getPostCssPlugin.js
post-preset-env 版本和 @builder/pack 内置的相同
> chore: avoid to rely on post-preset-env directly

- packages/plugin-rax-app/src/config/user.config.ts
Support case of remote devserver proxy where webpack hmr server side may validate origin.
> feat:add-allowedHosts-for-webpack

- packages/rax-webpack-config/CHANELOG.md
- packages/rax-webpack-config/package.json
- packages/rax-webpack-config/src/types.ts
- packages/rax-webpack-config/src/webpack.base.ts
@builder/pack/deps/webpack-chain
预打包之后 `require` 的行为发生变化，导致 plugin 没法 resolve 到
> chore: use webpack-chain directly

- packages/plugin-ssr/CHANGELOG.md
- packages/plugin-ssr/package.json
- packages/plugin-ssr/src/index.ts
- packages/plugin-ssr/src/ssr/EntryLoader.ts
- packages/plugin-ssr/src/ssr/addBuiltInRenderComponentToHTML.ts
- packages/plugin-ssr/src/ssr/addCustomRenderComponentToHTML.ts
- packages/plugin-ssr/src/ssr/entryPlugin.ts
- packages/plugin-ssr/src/ssr/setDev.ts
- packages/plugin-ssr/src/utils/formatEntryLoaderQuery.ts
- packages/plugin-ssr/src/utils/injectBundleInfo.ts
- packages/rax-app/package.json
- packages/rax-webpack-config/CHANELOG.md
- packages/rax-webpack-config/package.json
> fix: FaaS error case

- packages/plugin-rax-miniapp/src/index.js
结合 https://github.com/raxjs/miniapp/pull/296 一起看，修复编译时方案下，调用 `setAppConfig` 时 staticConfig.routes 过滤掉了 nativeRoutes，导致 `setEntry`（`setAppConfig` 中）执行过滤 nativeRoutes 时无结果，丢失了 nativeRoutes，最终产物中没将 `src/pages/` 路径下的 '原生小程序页面' 拷贝到产物目录 `build/miniapp/pages/` 下。
> fix(plugin-rax-miniapp): setAppCompileConfig staticConfig

- packages/plugin-rax-app/CHANGELOG.md
- packages/plugin-rax-app/package.json
- packages/plugin-rax-app/src/utils/logWebpackConfig.ts
用 JSON.stringify 的 replacer 解 cyclic object value 的方式，在 Node16 上面会 Crash，所以改用 util.inspect 实现. 问题参考：https://stackoverflow.com/questions/11616630/how-can-i-print-a-circular-structure-in-a-json-like-format
Node Crash 问题，主要出现在 less@^4 importManager.less.importManager 等循环场景，详见 https://code.alibaba-inc.com/clam-eco/clam/issues/550723
另外，仅在执行模式是 debug rax-app 时才执行 debug()，避免对普通 build 执行模式造成影响：功能 + 性能。
> fix(rax-app): debug()  run as needed and optimizing stringify
